
#Only one allowed
webhook:
    link: 

#ScanInterval
interval:
    seconds: 5

#Folders to watch, number of entries must be the same (3 folders, 3 colors)
watch:
    #Remember to escape windows paths -> \\
    folders:    
        - "C:\\"
        - "/home/pi"

    #HexColors only
    foldercolor:
        - "#336699"
        - "#17E427"
